title: "Test IT Blog"
description: "Test IT와 동일한 스타일의 블로그 테마"
baseurl: "" # 루트 URL
url: "https://test-it.co.kr" # 실제 사이트 URL

theme: test-it-theme
markdown: kramdown
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# 네비게이션 메뉴 설정
nav_links:
  - name: Home
    url: /
  - name: About
    url: /about/
  - name: Contact
    url: /contact/
